#jms_security_extra:
#    secure_all_services: true
#    expressions: true


security:
    access_denied_url:  /access-denied

    encoders:
       site:
         class:  MyFuckinJob\SiteBundle\Entity\Demandeur
         algorithm: sha512
         encode-as-base64: true
         iterations: 10



    providers:
      chain_provider:
          chain:
              providers: [site]
      site:
        entity: { class: MyFuckinJobSiteBundle:Demandeur, property: email }

    firewalls:
      site:
       pattern:    ^/
       security: true
       anonymous: true
       provider: site
       remember_me:
         always_remember_me: true
         key:      g46hqs4d9jqsdsd6g54h6sdyfhgadphfhgdldhjjhgjgm46sdfshg5qd1o
         lifetime: 720000
         path:     /
         domain:   ~ #Defaults to the current domain from $_SERVER
       form_login:
         use_forward:  true
         success_handler:  success_handler_site
         check_path:  /login_check
         login_path:  /login
         remember_me: true
       logout:
         path:   /logout
         target: /
         invalidate_session: false


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #        - { path: ^/partenaires/administration, roles: ROLE_PARTENAIRE }
    #        - { path: ^/administrator/, roles: ROLE_ADMIN }
        - { path: ^/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
      ROLE_USER:       ROLE_USER
#        ROLE_PARTENAIRE: [ROLE_PARTENAIRE,ROLE_USER,ROLE_ALLOWED_TO_SWITCH]
#        ROLE_ADMIN: [ROLE_ADMIN,ROLE_PARTENAIRE,ROLE_USER,ROLE_ALLOWED_TO_SWITCH]
