parameters:
#    my_fuckin_job_site.example.class: MyFuckinJob\SiteBundle\Example

services:
#    my_fuckin_job_site.example:
#        class: %my_fuckin_job_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
